"""Module contains SelectionSnapshot – the immutable snapshot of a tree selection."""
import logging
from dataclasses import dataclass, field

from src.pyssa.internal.data_structures.protein import Protein
from src.pyssa.internal.data_structures.protein_pair import ProteinPair
from src.pyssa.logging_pyssa import log_handlers

logger = logging.getLogger(__file__)
logger.addHandler(log_handlers.log_file_handler)

__docformat__ = "google"

@dataclass(frozen=True)
class SelectionSnapshot:
    """An immutable snapshot representing the current selection state of the PySSA objects tree.
    
    This class is generated by the PSAObjectsModel and emitted by the panel controller
    to ensure downstream controllers can safely query the selection state without
    worrying about Qt threading issues or traversing complex C++ models.
    """
    
    raw_sequences: set[str] = field(default_factory=set)
    raw_standalone_proteins: set[Protein] = field(default_factory=set)
    raw_protein_pair_children: set[Protein] = field(default_factory=set)
    raw_protein_pairs: set[ProteinPair] = field(default_factory=set)
    # The chempy classes aren't strongly typed in all contexts, so we'll use Any or basic objects 
    # but document them clearly. For our purposes, they are the chempy chain/residue/atom objects.
    raw_chains: set[object] = field(default_factory=set)
    raw_residues: set[object] = field(default_factory=set)
    raw_atoms: set[object] = field(default_factory=set)
    raw_scenes: set[str] = field(default_factory=set)
    pymol_selection_string: str = ""

    @property
    def distinct_proteins(self) -> set[Protein]:
        """Returns all selected proteins, including those derived from selected chains/residues/atoms."""
        return self.raw_standalone_proteins | self.raw_protein_pair_children

    @property
    def monomer_proteins(self) -> set[Protein]:
        """Returns all selected proteins that have only one chain."""
        return {p for p in self.distinct_proteins if len(p.chains) == 1}

    @property
    def multimer_proteins(self) -> set[Protein]:
        """Returns all selected proteins that have more than one chain."""
        return {p for p in self.distinct_proteins if len(p.chains) > 1}

    @property
    def monomer_sequences(self) -> set[str]:
        """Returns all selected sequences that represent monomers (no commas)."""
        return {s for s in self.raw_sequences if "," not in s}

    @property
    def multimer_sequences(self) -> set[str]:
        """Returns all selected sequences that represent multimers (contains commas)."""
        return {s for s in self.raw_sequences if "," in s}

    @property
    def has_monomer_sequences(self) -> bool:
        """Checks if any of the selected sequences are monomers."""
        return any("," not in s for s in self.raw_sequences)

    @property
    def has_multimer_sequences(self) -> bool:
        """Checks if any of the selected sequences are multimers."""
        return any("," in s for s in self.raw_sequences)

    @property
    def has_standalone_proteins(self) -> bool:
        """Checks if any standalone proteins are selected."""
        return len(self.raw_standalone_proteins) > 0

    @property
    def has_protein_pair_children(self) -> bool:
        """Checks if any proteins from protein pairs are selected."""
        return len(self.raw_protein_pair_children) > 0

    @property
    def has_protein_pairs(self) -> bool:
        """Checks if any protein pairs are selected."""
        return len(self.raw_protein_pairs) > 0

    def get_protein_pair_for_protein(self, protein: Protein) -> ProteinPair | None:
        """Find the protein pair that contains the given protein.

        Args:
            protein: The protein to find the parent pair for.

        Returns:
            The ProteinPair containing this protein, or None if not found or protein is standalone.
        """
        if protein in self.raw_standalone_proteins:
            return None

        for pair in self.raw_protein_pairs:
            if pair.protein_1 == protein or pair.protein_2 == protein:
                return pair

        return None
