site_name: PySSA
nav:
    - Home: index.md
    - Help:
        - help/index.md
        - Project:
            - Overview: help/project/index.md
            - New: help/project/new_project.md
            - Open: help/project/open_project.md
            - Delete: help/project/delete_project.md
            - Import: help/project/import_project.md
            - Export: help/project/export_project.md
        - Sequences:
            - Overview: help/sequences/index.md
            - Sequences Tab: help/sequences/sequences_tab.md
            - Additional Information Table: help/sequences/additional_sequence_information.md
            - Import Sequence: help/sequences/sequence_import.md
            - Add Sequence: help/sequences/sequence_add.md
            - Save Sequence: help/sequences/sequence_save.md
            - Delete Sequence: help/sequences/sequence_delete.md
        - Results:
              - Overview: help/results/index.md
              - Summary: help/results/summary.md
              - DD Visualizer: help/results/distance_data_visualizer.md
        - Guides:
              - Import FASTA File: help/sequences/guides/how_to_import_fasta_file.md
    - Screenshots:
          - screenshots/screenshot_open_project.md
    - About: about.md

theme:
    name: material
    logo: assets/images/pyssa_logo.png
    palette:
        primary: custom
    features:
        - navigation.tabs
        - navigation.instant
            - navigation.instant.progress
extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
        options:
          custom_icons:
            - overrides/.icons
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.superfences


copyright:
    Copyright © 2024 PySSA - Martin Urban & Hannah Kullik
