site_name: PySSA
nav:
    - Home: index.md
    - Help:
        - help/index.md
        - Project:
            - Overview: help/project/index.md
            - New: help/project/new_project.md
            - Open: help/project/open_project.md
            - Delete: help/project/delete_project.md
            - Import: help/project/import_project.md
            - Export: help/project/export_project.md
        - Sequences:
            - Overview: help/sequences/index.md
            - Sequences Tab: help/sequences/sequences_tab.md
            - Additional Information Table: help/sequences/additional_sequence_information.md
            - Import Sequence: help/sequences/sequence_import.md
            - Add Sequence: help/sequences/sequence_add.md
            - Save Sequence: help/sequences/sequence_save.md
            - Delete Sequence: help/sequences/sequence_delete.md
        - Proteins:
            - Overview: help/proteins/index.md
            - Proteins Tab: help/proteins/proteins_tab.md
            - Protein PyMOL Scene Configuration: help/proteins/protein_pymol_scene_configuration.md
            - Import Protein: help/proteins/protein_import.md
            - Save Protein: help/proteins/protein_save.md
            - Delete Protein: help/proteins/protein_delete.md
            - Load Protein PyMOL Session: help/proteins/protein_load_session.md
            - Add Protein PyMOL Scene: help/proteins/protein_add_scene.md
            - Update Protein PyMOL Scene: help/proteins/protein_update_scene.md
            - Delete Protein PyMOL Scene: help/proteins/protein_delete_scene.md
        - Protein Pairs:
              - Overview: help/protein_pairs/index.md
              - Protein Pairs Tab: help/protein_pairs/protein_pairs_tab.md
              - Delete Protein Pair: help/protein_pairs/protein_pair_delete.md
              - Load Protein Pair PyMOL Session: help/protein_pairs/protein_pair_load_session.md
              - Add Protein Pair PyMOL Scene: help/protein_pairs/protein_pair_add_scene.md
              - Update Protein Pair PyMOL Scene: help/protein_pairs/protein_pair_update_scene.md
              - Delete Protein Pair PyMOL Scene: help/protein_pairs/protein_pair_delete_scene.md
        - Protein Structure Prediction:
              - Overview: help/protein_structure_prediction/index.md
              - ColabFold Monomer Prediction: help/protein_structure_prediction/colabfold_monomer.md
              - ColabFold Multimer Prediction: help/protein_structure_prediction/colabfold_multimer.md
        - Protein Structure Analysis:
            - Overview: help/protein_structure_analysis/index.md
            - Distance Analysis: help/protein_structure_analysis/distance_analysis.md
        - Results:
              - Overview: help/results/index.md
              - Summary: help/results/summary.md
              - DD Visualizer: help/results/distance_data_visualizer.md
        - Hotspots:
            - Overview: help/hotspots/index.md
            - Protein Regions: help/hotspots/protein_regions.md
        - Images:
            - Overview: help/images/index.md
            - Preview Image: help/images/preview_image.md
            - Ray-Traced Image: help/images/ray_traced_image.md
            - Simple Image: help/images/simple_image.md
        - Settings:
            - Overview: help/settings/index.md
            - PySSA Settings: help/settings/pyssa_settings.md
        - Guides:
              - Import FASTA File: help/sequences/guides/how_to_import_fasta_file.md
    - Screenshots:
          - screenshots/screenshot_open_project.md
    - About: about.md

theme:
    name: material
    logo: assets/images/pyssa_logo.png
    palette:
        primary: custom
    features:
        - navigation.tabs
        - navigation.instant
            - navigation.instant.progress
extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
        options:
          custom_icons:
            - overrides/.icons
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.superfences


copyright:
    Copyright © 2024 PySSA - Martin Urban & Hannah Kullik
