# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow_alt.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(547, 747)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu_container = QtWidgets.QFrame(self.centralwidget)
        self.side_menu_container.setMinimumSize(QtCore.QSize(170, 0))
        self.side_menu_container.setMaximumSize(QtCore.QSize(170, 16777215))
        self.side_menu_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.side_menu_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu_container.setLineWidth(1)
        self.side_menu_container.setObjectName("side_menu_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.side_menu_container)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.side_menu = QtWidgets.QFrame(self.side_menu_container)
        self.side_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.side_menu.setFrameShape(QtWidgets.QFrame.Panel)
        self.side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu.setLineWidth(1)
        self.side_menu.setObjectName("side_menu")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.side_menu)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.project_name_frame = QtWidgets.QFrame(self.side_menu)
        self.project_name_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.project_name_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.project_name_frame.setObjectName("project_name_frame")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.project_name_frame)
        self.verticalLayout_22.setContentsMargins(8, 4, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.lbl_current_project_name = QtWidgets.QLabel(self.project_name_frame)
        self.lbl_current_project_name.setObjectName("lbl_current_project_name")
        self.verticalLayout_22.addWidget(self.lbl_current_project_name)
        self.verticalLayout_18.addWidget(self.project_name_frame)
        self.navigation_frame = QtWidgets.QFrame(self.side_menu)
        self.navigation_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.navigation_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navigation_frame.setObjectName("navigation_frame")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.navigation_frame)
        self.verticalLayout_24.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.lbl_project = QtWidgets.QLabel(self.navigation_frame)
        self.lbl_project.setObjectName("lbl_project")
        self.verticalLayout_23.addWidget(self.lbl_project)
        self.btn_new_page = QtWidgets.QPushButton(self.navigation_frame)
        self.btn_new_page.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_new_page.setObjectName("btn_new_page")
        self.verticalLayout_23.addWidget(self.btn_new_page)
        self.btn_open_page = QtWidgets.QPushButton(self.navigation_frame)
        self.btn_open_page.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_open_page.setObjectName("btn_open_page")
        self.verticalLayout_23.addWidget(self.btn_open_page)
        self.btn_delete_page = QtWidgets.QPushButton(self.navigation_frame)
        self.btn_delete_page.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_delete_page.setObjectName("btn_delete_page")
        self.verticalLayout_23.addWidget(self.btn_delete_page)
        self.verticalLayout_24.addLayout(self.verticalLayout_23)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_prediction = QtWidgets.QLabel(self.navigation_frame)
        self.lbl_prediction.setMaximumSize(QtCore.QSize(135, 16777215))
        self.lbl_prediction.setIndent(2)
        self.lbl_prediction.setObjectName("lbl_prediction")
        self.verticalLayout_2.addWidget(self.lbl_prediction)
        self.btn_prediction_only_page = QtWidgets.QPushButton(self.navigation_frame)
        self.btn_prediction_only_page.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_prediction_only_page.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_prediction_only_page.setCheckable(False)
        self.btn_prediction_only_page.setDefault(False)
        self.btn_prediction_only_page.setFlat(False)
        self.btn_prediction_only_page.setObjectName("btn_prediction_only_page")
        self.verticalLayout_2.addWidget(self.btn_prediction_only_page)
        self.btn_prediction_page = QtWidgets.QPushButton(self.navigation_frame)
        self.btn_prediction_page.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_prediction_page.setObjectName("btn_prediction_page")
        self.verticalLayout_2.addWidget(self.btn_prediction_page)
        self.verticalLayout_24.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbl_analysis = QtWidgets.QLabel(self.navigation_frame)
        self.lbl_analysis.setMaximumSize(QtCore.QSize(135, 16777215))
        self.lbl_analysis.setIndent(2)
        self.lbl_analysis.setObjectName("lbl_analysis")
        self.verticalLayout_5.addWidget(self.lbl_analysis)
        self.btn_single_analysis_page = QtWidgets.QPushButton(self.navigation_frame)
        self.btn_single_analysis_page.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_single_analysis_page.setObjectName("btn_single_analysis_page")
        self.verticalLayout_5.addWidget(self.btn_single_analysis_page)
        self.btn_job_analysis_page = QtWidgets.QPushButton(self.navigation_frame)
        self.btn_job_analysis_page.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_job_analysis_page.setObjectName("btn_job_analysis_page")
        self.verticalLayout_5.addWidget(self.btn_job_analysis_page)
        self.btn_results_page = QtWidgets.QPushButton(self.navigation_frame)
        self.btn_results_page.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_results_page.setObjectName("btn_results_page")
        self.verticalLayout_5.addWidget(self.btn_results_page)
        self.verticalLayout_24.addLayout(self.verticalLayout_5)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.lbl_handle_pymol_session = QtWidgets.QLabel(self.navigation_frame)
        self.lbl_handle_pymol_session.setMaximumSize(QtCore.QSize(135, 16777215))
        self.lbl_handle_pymol_session.setIndent(2)
        self.lbl_handle_pymol_session.setObjectName("lbl_handle_pymol_session")
        self.verticalLayout_17.addWidget(self.lbl_handle_pymol_session)
        self.btn_image_page = QtWidgets.QPushButton(self.navigation_frame)
        self.btn_image_page.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_image_page.setObjectName("btn_image_page")
        self.verticalLayout_17.addWidget(self.btn_image_page)
        self.btn_hotspots_page = QtWidgets.QPushButton(self.navigation_frame)
        self.btn_hotspots_page.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btn_hotspots_page.setCheckable(False)
        self.btn_hotspots_page.setObjectName("btn_hotspots_page")
        self.verticalLayout_17.addWidget(self.btn_hotspots_page)
        self.verticalLayout_24.addLayout(self.verticalLayout_17)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem)
        self.verticalLayout_18.addWidget(self.navigation_frame)
        self.verticalLayout.addWidget(self.side_menu)
        self.horizontalLayout.addWidget(self.side_menu_container)
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.gridLayout = QtWidgets.QGridLayout(self.main_body)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.top_navigation_bar_container = QtWidgets.QFrame(self.main_body)
        self.top_navigation_bar_container.setMaximumSize(QtCore.QSize(16777215, 50))
        self.top_navigation_bar_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_navigation_bar_container.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.top_navigation_bar_container.setMidLineWidth(0)
        self.top_navigation_bar_container.setObjectName("top_navigation_bar_container")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_navigation_bar_container)
        self.horizontalLayout_3.setContentsMargins(8, 4, 0, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_page_title = QtWidgets.QLabel(self.top_navigation_bar_container)
        self.lbl_page_title.setObjectName("lbl_page_title")
        self.horizontalLayout_3.addWidget(self.lbl_page_title)
        spacerItem1 = QtWidgets.QSpacerItem(363, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addWidget(self.top_navigation_bar_container, 0, 0, 1, 3)
        self.content = QtWidgets.QFrame(self.main_body)
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Plain)
        self.content.setLineWidth(1)
        self.content.setMidLineWidth(0)
        self.content.setObjectName("content")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.content)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content)
        self.stackedWidget.setMinimumSize(QtCore.QSize(353, 0))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_20.setContentsMargins(39, 60, -1, -1)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_3 = QtWidgets.QLabel(self.home_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(300, 300))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../assets/pyssa_logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setIndent(-1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_19.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.home_page)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setIndent(22)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_19.addWidget(self.label_4)
        self.verticalLayout_20.addLayout(self.verticalLayout_19)
        spacerItem2 = QtWidgets.QSpacerItem(20, 205, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.home_page)
        self.prediction_only_page = QtWidgets.QWidget()
        self.prediction_only_page.setObjectName("prediction_only_page")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.prediction_only_page)
        self.verticalLayout_16.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label = QtWidgets.QLabel(self.prediction_only_page)
        self.label.setObjectName("label")
        self.verticalLayout_16.addWidget(self.label)
        self.txt_prediction_only_notebook_url = QtWidgets.QLineEdit(self.prediction_only_page)
        self.txt_prediction_only_notebook_url.setObjectName("txt_prediction_only_notebook_url")
        self.verticalLayout_16.addWidget(self.txt_prediction_only_notebook_url)
        spacerItem3 = QtWidgets.QSpacerItem(20, 558, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem3)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_2 = QtWidgets.QLabel(self.prediction_only_page)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_21.addWidget(self.label_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem4)
        self.btn_prediction_only_start = QtWidgets.QPushButton(self.prediction_only_page)
        self.btn_prediction_only_start.setObjectName("btn_prediction_only_start")
        self.horizontalLayout_21.addWidget(self.btn_prediction_only_start)
        self.verticalLayout_16.addLayout(self.horizontalLayout_21)
        self.progress_bar_prediction_only = QtWidgets.QProgressBar(self.prediction_only_page)
        self.progress_bar_prediction_only.setProperty("value", 24)
        self.progress_bar_prediction_only.setObjectName("progress_bar_prediction_only")
        self.verticalLayout_16.addWidget(self.progress_bar_prediction_only)
        self.stackedWidget.addWidget(self.prediction_only_page)
        self.prediction_analysis_page = QtWidgets.QWidget()
        self.prediction_analysis_page.setObjectName("prediction_analysis_page")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.prediction_analysis_page)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_18 = QtWidgets.QLabel(self.prediction_analysis_page)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_21.addWidget(self.label_18)
        self.txt_prediction_project_name = QtWidgets.QLineEdit(self.prediction_analysis_page)
        self.txt_prediction_project_name.setObjectName("txt_prediction_project_name")
        self.verticalLayout_21.addWidget(self.txt_prediction_project_name)
        self.lbl_prediction_status_project_name = QtWidgets.QLabel(self.prediction_analysis_page)
        self.lbl_prediction_status_project_name.setObjectName("lbl_prediction_status_project_name")
        self.verticalLayout_21.addWidget(self.lbl_prediction_status_project_name)
        self.list_widget_projects = QtWidgets.QListWidget(self.prediction_analysis_page)
        self.list_widget_projects.setObjectName("list_widget_projects")
        self.verticalLayout_21.addWidget(self.list_widget_projects)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem5)
        self.btn_prediction_next_1 = QtWidgets.QPushButton(self.prediction_analysis_page)
        self.btn_prediction_next_1.setMaximumSize(QtCore.QSize(125, 16777215))
        self.btn_prediction_next_1.setMouseTracking(False)
        self.btn_prediction_next_1.setObjectName("btn_prediction_next_1")
        self.horizontalLayout_22.addWidget(self.btn_prediction_next_1)
        self.verticalLayout_21.addLayout(self.horizontalLayout_22)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_prediction_load_reference = QtWidgets.QLabel(self.prediction_analysis_page)
        self.lbl_prediction_load_reference.setObjectName("lbl_prediction_load_reference")
        self.verticalLayout_4.addWidget(self.lbl_prediction_load_reference)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.txt_prediction_load_reference = QtWidgets.QLineEdit(self.prediction_analysis_page)
        self.txt_prediction_load_reference.setObjectName("txt_prediction_load_reference")
        self.horizontalLayout_17.addWidget(self.txt_prediction_load_reference)
        self.btn_prediction_load_reference = QtWidgets.QToolButton(self.prediction_analysis_page)
        self.btn_prediction_load_reference.setObjectName("btn_prediction_load_reference")
        self.horizontalLayout_17.addWidget(self.btn_prediction_load_reference)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.lbl_prediction_status_load_reference = QtWidgets.QLabel(self.prediction_analysis_page)
        self.lbl_prediction_status_load_reference.setObjectName("lbl_prediction_status_load_reference")
        self.verticalLayout_4.addWidget(self.lbl_prediction_status_load_reference)
        self.verticalLayout_21.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.btn_prediction_back_2 = QtWidgets.QPushButton(self.prediction_analysis_page)
        self.btn_prediction_back_2.setMaximumSize(QtCore.QSize(125, 16777215))
        self.btn_prediction_back_2.setMouseTracking(False)
        self.btn_prediction_back_2.setObjectName("btn_prediction_back_2")
        self.horizontalLayout_2.addWidget(self.btn_prediction_back_2)
        self.btn_prediction_next_2 = QtWidgets.QPushButton(self.prediction_analysis_page)
        self.btn_prediction_next_2.setMaximumSize(QtCore.QSize(125, 16777215))
        self.btn_prediction_next_2.setMouseTracking(False)
        self.btn_prediction_next_2.setObjectName("btn_prediction_next_2")
        self.horizontalLayout_2.addWidget(self.btn_prediction_next_2)
        self.verticalLayout_21.addLayout(self.horizontalLayout_2)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.lbl_prediction_ref_chains = QtWidgets.QLabel(self.prediction_analysis_page)
        self.lbl_prediction_ref_chains.setObjectName("lbl_prediction_ref_chains")
        self.verticalLayout_14.addWidget(self.lbl_prediction_ref_chains)
        self.list_widget_ref_chains = QtWidgets.QListWidget(self.prediction_analysis_page)
        self.list_widget_ref_chains.setObjectName("list_widget_ref_chains")
        self.verticalLayout_14.addWidget(self.list_widget_ref_chains)
        self.lbl_prediction_model_chains = QtWidgets.QLabel(self.prediction_analysis_page)
        self.lbl_prediction_model_chains.setObjectName("lbl_prediction_model_chains")
        self.verticalLayout_14.addWidget(self.lbl_prediction_model_chains)
        self.txt_prediction_chain_model = QtWidgets.QLineEdit(self.prediction_analysis_page)
        self.txt_prediction_chain_model.setObjectName("txt_prediction_chain_model")
        self.verticalLayout_14.addWidget(self.txt_prediction_chain_model)
        self.verticalLayout_21.addLayout(self.verticalLayout_14)
        spacerItem7 = QtWidgets.QSpacerItem(20, 297, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem7)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem8)
        self.btn_prediction_back_3 = QtWidgets.QPushButton(self.prediction_analysis_page)
        self.btn_prediction_back_3.setMaximumSize(QtCore.QSize(125, 16777215))
        self.btn_prediction_back_3.setMouseTracking(False)
        self.btn_prediction_back_3.setObjectName("btn_prediction_back_3")
        self.horizontalLayout_18.addWidget(self.btn_prediction_back_3)
        self.btn_prediction_start = QtWidgets.QPushButton(self.prediction_analysis_page)
        self.btn_prediction_start.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_prediction_start.setMaximumSize(QtCore.QSize(125, 16777215))
        self.btn_prediction_start.setObjectName("btn_prediction_start")
        self.horizontalLayout_18.addWidget(self.btn_prediction_start)
        self.verticalLayout_21.addLayout(self.horizontalLayout_18)
        self.stackedWidget.addWidget(self.prediction_analysis_page)
        self.single_analysis_page = QtWidgets.QWidget()
        self.single_analysis_page.setObjectName("single_analysis_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.single_analysis_page)
        self.verticalLayout_7.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_19 = QtWidgets.QLabel(self.single_analysis_page)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_7.addWidget(self.label_19)
        self.txt_analysis_project_name = QtWidgets.QLineEdit(self.single_analysis_page)
        self.txt_analysis_project_name.setObjectName("txt_analysis_project_name")
        self.verticalLayout_7.addWidget(self.txt_analysis_project_name)
        self.label_20 = QtWidgets.QLabel(self.single_analysis_page)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_7.addWidget(self.label_20)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.txt_analysis_load_reference = QtWidgets.QLineEdit(self.single_analysis_page)
        self.txt_analysis_load_reference.setObjectName("txt_analysis_load_reference")
        self.horizontalLayout_19.addWidget(self.txt_analysis_load_reference)
        self.btn_analysis_load_reference = QtWidgets.QToolButton(self.single_analysis_page)
        self.btn_analysis_load_reference.setObjectName("btn_analysis_load_reference")
        self.horizontalLayout_19.addWidget(self.btn_analysis_load_reference)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_analysis_load_model = QtWidgets.QPushButton(self.single_analysis_page)
        self.btn_analysis_load_model.setMinimumSize(QtCore.QSize(180, 0))
        self.btn_analysis_load_model.setObjectName("btn_analysis_load_model")
        self.horizontalLayout_4.addWidget(self.btn_analysis_load_model)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.txt_analysis_load_model = QtWidgets.QTextEdit(self.single_analysis_page)
        self.txt_analysis_load_model.setEnabled(False)
        self.txt_analysis_load_model.setMaximumSize(QtCore.QSize(16777215, 40))
        self.txt_analysis_load_model.setObjectName("txt_analysis_load_model")
        self.verticalLayout_7.addWidget(self.txt_analysis_load_model)
        self.cb_analysis_chain_info = QtWidgets.QCheckBox(self.single_analysis_page)
        self.cb_analysis_chain_info.setObjectName("cb_analysis_chain_info")
        self.verticalLayout_7.addWidget(self.cb_analysis_chain_info)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.single_analysis_page)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.txt_analysis_chain_ref = QtWidgets.QLineEdit(self.single_analysis_page)
        self.txt_analysis_chain_ref.setObjectName("txt_analysis_chain_ref")
        self.verticalLayout_6.addWidget(self.txt_analysis_chain_ref)
        self.label_6 = QtWidgets.QLabel(self.single_analysis_page)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.txt_analysis_chain_model = QtWidgets.QLineEdit(self.single_analysis_page)
        self.txt_analysis_chain_model.setObjectName("txt_analysis_chain_model")
        self.verticalLayout_6.addWidget(self.txt_analysis_chain_model)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        spacerItem10 = QtWidgets.QSpacerItem(20, 328, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem10)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.single_analysis_page)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.btn_analysis_start = QtWidgets.QPushButton(self.single_analysis_page)
        self.btn_analysis_start.setObjectName("btn_analysis_start")
        self.horizontalLayout_5.addWidget(self.btn_analysis_start)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.progress_bar_analysis = QtWidgets.QProgressBar(self.single_analysis_page)
        self.progress_bar_analysis.setProperty("value", 24)
        self.progress_bar_analysis.setObjectName("progress_bar_analysis")
        self.verticalLayout_7.addWidget(self.progress_bar_analysis)
        self.stackedWidget.addWidget(self.single_analysis_page)
        self.job_analysis_page = QtWidgets.QWidget()
        self.job_analysis_page.setObjectName("job_analysis_page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.job_analysis_page)
        self.verticalLayout_8.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_21 = QtWidgets.QLabel(self.job_analysis_page)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_8.addWidget(self.label_21)
        self.txt_batch_job_name = QtWidgets.QLineEdit(self.job_analysis_page)
        self.txt_batch_job_name.setObjectName("txt_batch_job_name")
        self.verticalLayout_8.addWidget(self.txt_batch_job_name)
        self.label_22 = QtWidgets.QLabel(self.job_analysis_page)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_8.addWidget(self.label_22)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.txt_batch_load_reference = QtWidgets.QLineEdit(self.job_analysis_page)
        self.txt_batch_load_reference.setObjectName("txt_batch_load_reference")
        self.horizontalLayout_20.addWidget(self.txt_batch_load_reference)
        self.btn_batch_load_reference = QtWidgets.QToolButton(self.job_analysis_page)
        self.btn_batch_load_reference.setObjectName("btn_batch_load_reference")
        self.horizontalLayout_20.addWidget(self.btn_batch_load_reference)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btn_batch_load_model = QtWidgets.QPushButton(self.job_analysis_page)
        self.btn_batch_load_model.setMinimumSize(QtCore.QSize(180, 0))
        self.btn_batch_load_model.setObjectName("btn_batch_load_model")
        self.horizontalLayout_15.addWidget(self.btn_batch_load_model)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem12)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.txt_batch_load_model = QtWidgets.QTextEdit(self.job_analysis_page)
        self.txt_batch_load_model.setEnabled(False)
        self.txt_batch_load_model.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txt_batch_load_model.setObjectName("txt_batch_load_model")
        self.verticalLayout_8.addWidget(self.txt_batch_load_model)
        self.cb_batch_chain_info = QtWidgets.QCheckBox(self.job_analysis_page)
        self.cb_batch_chain_info.setObjectName("cb_batch_chain_info")
        self.verticalLayout_8.addWidget(self.cb_batch_chain_info)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.job_analysis_page)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_11.addWidget(self.label_11)
        self.txt_batch_chain_ref = QtWidgets.QLineEdit(self.job_analysis_page)
        self.txt_batch_chain_ref.setObjectName("txt_batch_chain_ref")
        self.verticalLayout_11.addWidget(self.txt_batch_chain_ref)
        self.label_12 = QtWidgets.QLabel(self.job_analysis_page)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.txt_batch_chain_model = QtWidgets.QLineEdit(self.job_analysis_page)
        self.txt_batch_chain_model.setObjectName("txt_batch_chain_model")
        self.verticalLayout_11.addWidget(self.txt_batch_chain_model)
        self.verticalLayout_8.addLayout(self.verticalLayout_11)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.job_analysis_page)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem13)
        self.btn_batch_start = QtWidgets.QPushButton(self.job_analysis_page)
        self.btn_batch_start.setObjectName("btn_batch_start")
        self.horizontalLayout_16.addWidget(self.btn_batch_start)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.progress_bar_batch = QtWidgets.QProgressBar(self.job_analysis_page)
        self.progress_bar_batch.setProperty("value", 24)
        self.progress_bar_batch.setObjectName("progress_bar_batch")
        self.verticalLayout_8.addWidget(self.progress_bar_batch)
        self.stackedWidget.addWidget(self.job_analysis_page)
        self.results_page = QtWidgets.QWidget()
        self.results_page.setObjectName("results_page")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.results_page)
        self.verticalLayout_12.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_view_distance_plot = QtWidgets.QPushButton(self.results_page)
        self.btn_view_distance_plot.setObjectName("btn_view_distance_plot")
        self.horizontalLayout_10.addWidget(self.btn_view_distance_plot)
        self.btn_view_struct_alignment = QtWidgets.QPushButton(self.results_page)
        self.btn_view_struct_alignment.setObjectName("btn_view_struct_alignment")
        self.horizontalLayout_10.addWidget(self.btn_view_struct_alignment)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btn_view_distance_histogram = QtWidgets.QPushButton(self.results_page)
        self.btn_view_distance_histogram.setObjectName("btn_view_distance_histogram")
        self.horizontalLayout_11.addWidget(self.btn_view_distance_histogram)
        self.btn_view_distance_table = QtWidgets.QPushButton(self.results_page)
        self.btn_view_distance_table.setObjectName("btn_view_distance_table")
        self.horizontalLayout_11.addWidget(self.btn_view_distance_table)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.cb_interesting_regions = QtWidgets.QComboBox(self.results_page)
        self.cb_interesting_regions.setObjectName("cb_interesting_regions")
        self.verticalLayout_10.addWidget(self.cb_interesting_regions)
        self.btn_view_interesting_region = QtWidgets.QPushButton(self.results_page)
        self.btn_view_interesting_region.setObjectName("btn_view_interesting_region")
        self.verticalLayout_10.addWidget(self.btn_view_interesting_region)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.results_page)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.project_list = QtWidgets.QListWidget(self.results_page)
        self.project_list.setObjectName("project_list")
        self.verticalLayout_9.addWidget(self.project_list)
        self.verticalLayout_12.addLayout(self.verticalLayout_9)
        spacerItem14 = QtWidgets.QSpacerItem(20, 284, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem14)
        self.stackedWidget.addWidget(self.results_page)
        self.image_page = QtWidgets.QWidget()
        self.image_page.setObjectName("image_page")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.image_page)
        self.verticalLayout_15.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_25 = QtWidgets.QLabel(self.image_page)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_13.addWidget(self.label_25)
        self.box_representation = QtWidgets.QComboBox(self.image_page)
        self.box_representation.setObjectName("box_representation")
        self.horizontalLayout_13.addWidget(self.box_representation)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_24 = QtWidgets.QLabel(self.image_page)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_12.addWidget(self.label_24)
        self.box_bg_color = QtWidgets.QComboBox(self.image_page)
        self.box_bg_color.setObjectName("box_bg_color")
        self.horizontalLayout_12.addWidget(self.box_bg_color)
        self.verticalLayout_15.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.image_page)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.box_renderer = QtWidgets.QComboBox(self.image_page)
        self.box_renderer.setObjectName("box_renderer")
        self.horizontalLayout_8.addWidget(self.box_renderer)
        self.verticalLayout_15.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.image_page)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.box_ray_trace_mode = QtWidgets.QComboBox(self.image_page)
        self.box_ray_trace_mode.setObjectName("box_ray_trace_mode")
        self.horizontalLayout_6.addWidget(self.box_ray_trace_mode)
        self.verticalLayout_15.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.image_page)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.box_ray_texture = QtWidgets.QComboBox(self.image_page)
        self.box_ray_texture.setObjectName("box_ray_texture")
        self.horizontalLayout_7.addWidget(self.box_ray_texture)
        self.verticalLayout_15.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_26 = QtWidgets.QLabel(self.image_page)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_14.addWidget(self.label_26)
        self.cb_ray_tracing = QtWidgets.QCheckBox(self.image_page)
        self.cb_ray_tracing.setText("")
        self.cb_ray_tracing.setObjectName("cb_ray_tracing")
        self.horizontalLayout_14.addWidget(self.cb_ray_tracing)
        self.verticalLayout_15.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_23 = QtWidgets.QLabel(self.image_page)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_9.addWidget(self.label_23)
        self.cb_transparent_bg = QtWidgets.QCheckBox(self.image_page)
        self.cb_transparent_bg.setText("")
        self.cb_transparent_bg.setObjectName("cb_transparent_bg")
        self.horizontalLayout_9.addWidget(self.cb_transparent_bg)
        self.verticalLayout_15.addLayout(self.horizontalLayout_9)
        spacerItem15 = QtWidgets.QSpacerItem(20, 349, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem15)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.btn_save_scene = QtWidgets.QPushButton(self.image_page)
        self.btn_save_scene.setObjectName("btn_save_scene")
        self.verticalLayout_13.addWidget(self.btn_save_scene)
        self.btn_update_scene = QtWidgets.QPushButton(self.image_page)
        self.btn_update_scene.setObjectName("btn_update_scene")
        self.verticalLayout_13.addWidget(self.btn_update_scene)
        self.btn_preview_image = QtWidgets.QPushButton(self.image_page)
        self.btn_preview_image.setObjectName("btn_preview_image")
        self.verticalLayout_13.addWidget(self.btn_preview_image)
        self.btn_save_image = QtWidgets.QPushButton(self.image_page)
        self.btn_save_image.setObjectName("btn_save_image")
        self.verticalLayout_13.addWidget(self.btn_save_image)
        self.verticalLayout_15.addLayout(self.verticalLayout_13)
        self.stackedWidget.addWidget(self.image_page)
        self.create_new_project = QtWidgets.QWidget()
        self.create_new_project.setObjectName("create_new_project")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.create_new_project)
        self.verticalLayout_38.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout_38.setSpacing(10)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.main_open_frame = QtWidgets.QFrame(self.create_new_project)
        self.main_open_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_open_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_open_frame.setObjectName("main_open_frame")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.main_open_frame)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setSpacing(2)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_17 = QtWidgets.QLabel(self.main_open_frame)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_26.addWidget(self.label_17)
        self.txt_new_project_name = QtWidgets.QLineEdit(self.main_open_frame)
        self.txt_new_project_name.setObjectName("txt_new_project_name")
        self.verticalLayout_26.addWidget(self.txt_new_project_name)
        self.lbl_new_status_project_name = QtWidgets.QLabel(self.main_open_frame)
        self.lbl_new_status_project_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_new_status_project_name.setIndent(-1)
        self.lbl_new_status_project_name.setObjectName("lbl_new_status_project_name")
        self.verticalLayout_26.addWidget(self.lbl_new_status_project_name)
        self.verticalLayout_27.addLayout(self.verticalLayout_26)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setSpacing(3)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_27 = QtWidgets.QLabel(self.main_open_frame)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_25.addWidget(self.label_27)
        self.list_new_projects = QtWidgets.QListWidget(self.main_open_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_new_projects.sizePolicy().hasHeightForWidth())
        self.list_new_projects.setSizePolicy(sizePolicy)
        self.list_new_projects.setMinimumSize(QtCore.QSize(0, 0))
        self.list_new_projects.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.list_new_projects.setObjectName("list_new_projects")
        self.verticalLayout_25.addWidget(self.list_new_projects)
        self.verticalLayout_27.addLayout(self.verticalLayout_25)
        self.verticalLayout_38.addWidget(self.main_open_frame)
        self.frame = QtWidgets.QFrame(self.create_new_project)
        self.frame.setMinimumSize(QtCore.QSize(0, 86))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 86))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_37.setSpacing(6)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.cb_new_add_reference = QtWidgets.QCheckBox(self.frame)
        self.cb_new_add_reference.setCheckable(True)
        self.cb_new_add_reference.setObjectName("cb_new_add_reference")
        self.verticalLayout_37.addWidget(self.cb_new_add_reference)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setSpacing(2)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.lbl_new_choose_reference = QtWidgets.QLabel(self.frame)
        self.lbl_new_choose_reference.setObjectName("lbl_new_choose_reference")
        self.verticalLayout_36.addWidget(self.lbl_new_choose_reference)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.txt_new_choose_reference = QtWidgets.QLineEdit(self.frame)
        self.txt_new_choose_reference.setObjectName("txt_new_choose_reference")
        self.horizontalLayout_26.addWidget(self.txt_new_choose_reference)
        self.btn_new_choose_reference = QtWidgets.QToolButton(self.frame)
        self.btn_new_choose_reference.setObjectName("btn_new_choose_reference")
        self.horizontalLayout_26.addWidget(self.btn_new_choose_reference)
        self.verticalLayout_36.addLayout(self.horizontalLayout_26)
        self.lbl_new_status_choose_reference = QtWidgets.QLabel(self.frame)
        self.lbl_new_status_choose_reference.setObjectName("lbl_new_status_choose_reference")
        self.verticalLayout_36.addWidget(self.lbl_new_status_choose_reference)
        self.verticalLayout_37.addLayout(self.verticalLayout_36)
        self.verticalLayout_38.addWidget(self.frame)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem16 = QtWidgets.QSpacerItem(198, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem16)
        self.btn_new_create_project = QtWidgets.QPushButton(self.create_new_project)
        self.btn_new_create_project.setObjectName("btn_new_create_project")
        self.horizontalLayout_23.addWidget(self.btn_new_create_project)
        self.verticalLayout_38.addLayout(self.horizontalLayout_23)
        self.stackedWidget.addWidget(self.create_new_project)
        self.open_project = QtWidgets.QWidget()
        self.open_project.setObjectName("open_project")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.open_project)
        self.verticalLayout_31.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setSpacing(2)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_28 = QtWidgets.QLabel(self.open_project)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_28.addWidget(self.label_28)
        self.txt_open_search = QtWidgets.QLineEdit(self.open_project)
        self.txt_open_search.setObjectName("txt_open_search")
        self.verticalLayout_28.addWidget(self.txt_open_search)
        self.lbl_open_status_search = QtWidgets.QLabel(self.open_project)
        self.lbl_open_status_search.setObjectName("lbl_open_status_search")
        self.verticalLayout_28.addWidget(self.lbl_open_status_search)
        self.verticalLayout_31.addLayout(self.verticalLayout_28)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setSpacing(3)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_29 = QtWidgets.QLabel(self.open_project)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_29.addWidget(self.label_29)
        self.list_open_projects = QtWidgets.QListWidget(self.open_project)
        self.list_open_projects.setObjectName("list_open_projects")
        self.verticalLayout_29.addWidget(self.list_open_projects)
        self.verticalLayout_31.addLayout(self.verticalLayout_29)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setSpacing(2)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_30 = QtWidgets.QLabel(self.open_project)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_30.addWidget(self.label_30)
        self.txt_open_selected_project = QtWidgets.QLineEdit(self.open_project)
        self.txt_open_selected_project.setReadOnly(True)
        self.txt_open_selected_project.setObjectName("txt_open_selected_project")
        self.verticalLayout_30.addWidget(self.txt_open_selected_project)
        self.verticalLayout_31.addLayout(self.verticalLayout_30)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem17)
        self.btn_open_open_project = QtWidgets.QPushButton(self.open_project)
        self.btn_open_open_project.setObjectName("btn_open_open_project")
        self.horizontalLayout_24.addWidget(self.btn_open_open_project)
        self.verticalLayout_31.addLayout(self.horizontalLayout_24)
        self.stackedWidget.addWidget(self.open_project)
        self.delete_project = QtWidgets.QWidget()
        self.delete_project.setObjectName("delete_project")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.delete_project)
        self.verticalLayout_35.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setSpacing(2)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_31 = QtWidgets.QLabel(self.delete_project)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_32.addWidget(self.label_31)
        self.txt_delete_search = QtWidgets.QLineEdit(self.delete_project)
        self.txt_delete_search.setObjectName("txt_delete_search")
        self.verticalLayout_32.addWidget(self.txt_delete_search)
        self.lbl_delete_status_search = QtWidgets.QLabel(self.delete_project)
        self.lbl_delete_status_search.setObjectName("lbl_delete_status_search")
        self.verticalLayout_32.addWidget(self.lbl_delete_status_search)
        self.verticalLayout_35.addLayout(self.verticalLayout_32)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setSpacing(3)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_32 = QtWidgets.QLabel(self.delete_project)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_33.addWidget(self.label_32)
        self.list_delete_projects = QtWidgets.QListWidget(self.delete_project)
        self.list_delete_projects.setObjectName("list_delete_projects")
        self.verticalLayout_33.addWidget(self.list_delete_projects)
        self.verticalLayout_35.addLayout(self.verticalLayout_33)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setSpacing(2)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_33 = QtWidgets.QLabel(self.delete_project)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_34.addWidget(self.label_33)
        self.txt_delete_selected_projects = QtWidgets.QLineEdit(self.delete_project)
        self.txt_delete_selected_projects.setReadOnly(True)
        self.txt_delete_selected_projects.setObjectName("txt_delete_selected_projects")
        self.verticalLayout_34.addWidget(self.txt_delete_selected_projects)
        self.verticalLayout_35.addLayout(self.verticalLayout_34)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem18)
        self.btn_delete_delete_project = QtWidgets.QPushButton(self.delete_project)
        self.btn_delete_delete_project.setObjectName("btn_delete_delete_project")
        self.horizontalLayout_25.addWidget(self.btn_delete_delete_project)
        self.verticalLayout_35.addLayout(self.horizontalLayout_25)
        self.stackedWidget.addWidget(self.delete_project)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.content, 1, 0, 1, 3)
        self.horizontalLayout.addWidget(self.main_body)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 547, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuWizard = QtWidgets.QMenu(self.menubar)
        self.menuWizard.setObjectName("menuWizard")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_file_open = QtWidgets.QAction(MainWindow)
        self.action_file_open.setObjectName("action_file_open")
        self.action_settings_edit_all = QtWidgets.QAction(MainWindow)
        self.action_settings_edit_all.setObjectName("action_settings_edit_all")
        self.action_file_save_as = QtWidgets.QAction(MainWindow)
        self.action_file_save_as.setObjectName("action_file_save_as")
        self.action_file_save = QtWidgets.QAction(MainWindow)
        self.action_file_save.setObjectName("action_file_save")
        self.action_file_quit = QtWidgets.QAction(MainWindow)
        self.action_file_quit.setObjectName("action_file_quit")
        self.action_settings_model_w_off_colab_notebook = QtWidgets.QAction(MainWindow)
        self.action_settings_model_w_off_colab_notebook.setCheckable(True)
        self.action_settings_model_w_off_colab_notebook.setObjectName("action_settings_model_w_off_colab_notebook")
        self.action_file_restore_settings = QtWidgets.QAction(MainWindow)
        self.action_file_restore_settings.setObjectName("action_file_restore_settings")
        self.action_wizard_prepare_model_pdbs = QtWidgets.QAction(MainWindow)
        self.action_wizard_prepare_model_pdbs.setObjectName("action_wizard_prepare_model_pdbs")
        self.action_display_current_workspace = QtWidgets.QAction(MainWindow)
        self.action_display_current_workspace.setObjectName("action_display_current_workspace")
        self.action_display_project_path = QtWidgets.QAction(MainWindow)
        self.action_display_project_path.setObjectName("action_display_project_path")
        self.action_help_docs = QtWidgets.QAction(MainWindow)
        self.action_help_docs.setObjectName("action_help_docs")
        self.action_help_docs_pdf = QtWidgets.QAction(MainWindow)
        self.action_help_docs_pdf.setObjectName("action_help_docs_pdf")
        self.action_help_about = QtWidgets.QAction(MainWindow)
        self.action_help_about.setObjectName("action_help_about")
        self.action_add_model = QtWidgets.QAction(MainWindow)
        self.action_add_model.setObjectName("action_add_model")
        self.menuFile.addAction(self.action_file_open)
        self.menuFile.addAction(self.action_file_save)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_file_quit)
        self.menuSettings.addAction(self.action_settings_edit_all)
        self.menuSettings.addAction(self.action_settings_model_w_off_colab_notebook)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.action_file_restore_settings)
        self.menuWizard.addAction(self.action_file_save_as)
        self.menuWizard.addAction(self.action_add_model)
        self.menuHelp.addAction(self.action_help_docs)
        self.menuHelp.addAction(self.action_help_docs_pdf)
        self.menuHelp.addAction(self.action_help_about)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWizard.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_current_project_name.setText(_translate("MainWindow", "hhhhhhhhhhhhhhhhhhhh"))
        self.lbl_project.setText(_translate("MainWindow", "Project"))
        self.btn_new_page.setText(_translate("MainWindow", "New ..."))
        self.btn_open_page.setText(_translate("MainWindow", "Open ..."))
        self.btn_delete_page.setText(_translate("MainWindow", "Delete ..."))
        self.lbl_prediction.setText(_translate("MainWindow", "Prediction"))
        self.btn_prediction_only_page.setText(_translate("MainWindow", "New Sequence"))
        self.btn_prediction_page.setText(_translate("MainWindow", "Sequence vs .pdb"))
        self.lbl_analysis.setText(_translate("MainWindow", "Analysis"))
        self.btn_single_analysis_page.setText(_translate("MainWindow", "Single Analysis"))
        self.btn_job_analysis_page.setText(_translate("MainWindow", "Job Analysis"))
        self.btn_results_page.setText(_translate("MainWindow", "Results"))
        self.lbl_handle_pymol_session.setText(_translate("MainWindow", "PyMOL Session"))
        self.btn_image_page.setText(_translate("MainWindow", "Image"))
        self.btn_hotspots_page.setText(_translate("MainWindow", "Hotspots"))
        self.lbl_page_title.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "PySSA - Python-Plugin for Sequence-to-Structure Analysis"))
        self.label.setText(_translate("MainWindow", "Notebook URL:"))
        self.label_2.setText(_translate("MainWindow", "Predict with Colab Notebook"))
        self.btn_prediction_only_start.setText(_translate("MainWindow", "Start"))
        self.label_18.setText(_translate("MainWindow", "Enter a new project name:"))
        self.lbl_prediction_status_project_name.setText(_translate("MainWindow", "TextLabel"))
        self.btn_prediction_next_1.setText(_translate("MainWindow", "Next"))
        self.lbl_prediction_load_reference.setText(_translate("MainWindow", "Choose a reference .pdb file or enter a PDB ID:"))
        self.btn_prediction_load_reference.setText(_translate("MainWindow", "..."))
        self.lbl_prediction_status_load_reference.setText(_translate("MainWindow", "TextLabel"))
        self.btn_prediction_back_2.setText(_translate("MainWindow", "Back"))
        self.btn_prediction_next_2.setText(_translate("MainWindow", "Next"))
        self.lbl_prediction_ref_chains.setText(_translate("MainWindow", "Select chains in reference if necessary:"))
        self.lbl_prediction_model_chains.setText(_translate("MainWindow", "Chains in model"))
        self.btn_prediction_back_3.setText(_translate("MainWindow", "Back"))
        self.btn_prediction_start.setText(_translate("MainWindow", "Start"))
        self.label_19.setText(_translate("MainWindow", "Enter a project name:"))
        self.label_20.setText(_translate("MainWindow", "Choose a .pdb file or enter a PDB ID:"))
        self.btn_analysis_load_reference.setText(_translate("MainWindow", "..."))
        self.btn_analysis_load_model.setText(_translate("MainWindow", "Open model"))
        self.cb_analysis_chain_info.setText(_translate("MainWindow", "Add chain information"))
        self.label_5.setText(_translate("MainWindow", "Chains in reference (input style: G,H)"))
        self.label_6.setText(_translate("MainWindow", "Chains in models (input style: A,B)"))
        self.label_7.setText(_translate("MainWindow", "Structure prediction analysis"))
        self.btn_analysis_start.setText(_translate("MainWindow", "Start"))
        self.label_21.setText(_translate("MainWindow", "Enter a job name:"))
        self.label_22.setText(_translate("MainWindow", "Choose a .pdb file or enter a PDB ID:"))
        self.btn_batch_load_reference.setText(_translate("MainWindow", "..."))
        self.btn_batch_load_model.setText(_translate("MainWindow", "Open models"))
        self.cb_batch_chain_info.setText(_translate("MainWindow", "Add chain information"))
        self.label_11.setText(_translate("MainWindow", "Chains in reference (input style: G,H)"))
        self.label_12.setText(_translate("MainWindow", "Chains in models (input style: A,B)"))
        self.label_13.setText(_translate("MainWindow", "Batch structure analysis"))
        self.btn_batch_start.setText(_translate("MainWindow", "Start"))
        self.btn_view_distance_plot.setText(_translate("MainWindow", "View distance plot"))
        self.btn_view_struct_alignment.setText(_translate("MainWindow", "View structure alignment"))
        self.btn_view_distance_histogram.setText(_translate("MainWindow", "View distance histogram"))
        self.btn_view_distance_table.setText(_translate("MainWindow", "View distance table"))
        self.btn_view_interesting_region.setText(_translate("MainWindow", "View interesting region"))
        self.label_9.setText(_translate("MainWindow", "Project List:"))
        self.label_25.setText(_translate("MainWindow", "Representation"))
        self.label_24.setText(_translate("MainWindow", "Background Color"))
        self.label_8.setText(_translate("MainWindow", "Renderer"))
        self.label_10.setText(_translate("MainWindow", "Ray-Trace-Mode"))
        self.label_14.setText(_translate("MainWindow", "Ray Texture"))
        self.label_26.setText(_translate("MainWindow", "Ray-Tracing"))
        self.label_23.setText(_translate("MainWindow", "Transparent Background"))
        self.btn_save_scene.setText(_translate("MainWindow", "Save Scene"))
        self.btn_update_scene.setText(_translate("MainWindow", "Update Scene"))
        self.btn_preview_image.setText(_translate("MainWindow", "Preview Image"))
        self.btn_save_image.setText(_translate("MainWindow", "Save Image"))
        self.label_17.setText(_translate("MainWindow", "Enter new project name"))
        self.lbl_new_status_project_name.setText(_translate("MainWindow", "TextLabel"))
        self.label_27.setText(_translate("MainWindow", "Existing projects"))
        self.cb_new_add_reference.setText(_translate("MainWindow", "Add reference protein"))
        self.lbl_new_choose_reference.setText(_translate("MainWindow", "Choose a reference .pdb file or enter a PDB ID"))
        self.btn_new_choose_reference.setText(_translate("MainWindow", "..."))
        self.lbl_new_status_choose_reference.setText(_translate("MainWindow", "TextLabel"))
        self.btn_new_create_project.setText(_translate("MainWindow", "Create"))
        self.label_28.setText(_translate("MainWindow", "Search"))
        self.lbl_open_status_search.setText(_translate("MainWindow", "TextLabel"))
        self.label_29.setText(_translate("MainWindow", "Existing projects"))
        self.label_30.setText(_translate("MainWindow", "Selected project"))
        self.btn_open_open_project.setText(_translate("MainWindow", "Open"))
        self.label_31.setText(_translate("MainWindow", "Search"))
        self.lbl_delete_status_search.setText(_translate("MainWindow", "TextLabel"))
        self.label_32.setText(_translate("MainWindow", "Existing projects"))
        self.label_33.setText(_translate("MainWindow", "Selected project"))
        self.btn_delete_delete_project.setText(_translate("MainWindow", "Delete"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuWizard.setTitle(_translate("MainWindow", "Expert"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.action_file_open.setText(_translate("MainWindow", "Open"))
        self.action_settings_edit_all.setText(_translate("MainWindow", "Edit all"))
        self.action_file_save_as.setText(_translate("MainWindow", "Save PyMOL session as"))
        self.action_file_save.setText(_translate("MainWindow", "Save"))
        self.action_file_quit.setText(_translate("MainWindow", "Quit"))
        self.action_settings_model_w_off_colab_notebook.setText(_translate("MainWindow", "Modeling with official colab notebook"))
        self.action_file_restore_settings.setText(_translate("MainWindow", "Restore Settings"))
        self.action_wizard_prepare_model_pdbs.setText(_translate("MainWindow", "Prepare Models"))
        self.action_display_current_workspace.setText(_translate("MainWindow", "Current Workspace"))
        self.action_display_project_path.setText(_translate("MainWindow", "Current Project Path"))
        self.action_help_docs.setText(_translate("MainWindow", "Documentation"))
        self.action_help_docs_pdf.setText(_translate("MainWindow", "Documentation PDF"))
        self.action_help_about.setText(_translate("MainWindow", "About"))
        self.action_add_model.setText(_translate("MainWindow", "Add Model"))

