# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 747)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_13.addWidget(self.label_18)
        self.txt_prediction_project_name = QtWidgets.QLineEdit(self.tab_6)
        self.txt_prediction_project_name.setObjectName("txt_prediction_project_name")
        self.verticalLayout_13.addWidget(self.txt_prediction_project_name)
        self.label_15 = QtWidgets.QLabel(self.tab_6)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_13.addWidget(self.label_15)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.txt_prediction_load_reference = QtWidgets.QLineEdit(self.tab_6)
        self.txt_prediction_load_reference.setObjectName("txt_prediction_load_reference")
        self.horizontalLayout_17.addWidget(self.txt_prediction_load_reference)
        self.btn_prediction_load_reference = QtWidgets.QToolButton(self.tab_6)
        self.btn_prediction_load_reference.setObjectName("btn_prediction_load_reference")
        self.horizontalLayout_17.addWidget(self.btn_prediction_load_reference)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        self.cb_prediction_chain_info = QtWidgets.QCheckBox(self.tab_6)
        self.cb_prediction_chain_info.setObjectName("cb_prediction_chain_info")
        self.verticalLayout_13.addWidget(self.cb_prediction_chain_info)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_16 = QtWidgets.QLabel(self.tab_6)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_14.addWidget(self.label_16)
        self.txt_prediction_chain_ref = QtWidgets.QLineEdit(self.tab_6)
        self.txt_prediction_chain_ref.setObjectName("txt_prediction_chain_ref")
        self.verticalLayout_14.addWidget(self.txt_prediction_chain_ref)
        self.label_17 = QtWidgets.QLabel(self.tab_6)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_14.addWidget(self.label_17)
        self.txt_prediction_chain_model = QtWidgets.QLineEdit(self.tab_6)
        self.txt_prediction_chain_model.setObjectName("txt_prediction_chain_model")
        self.verticalLayout_14.addWidget(self.txt_prediction_chain_model)
        self.verticalLayout_13.addLayout(self.verticalLayout_14)
        spacerItem = QtWidgets.QSpacerItem(20, 195, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.btn_prediction_cancel = QtWidgets.QPushButton(self.tab_6)
        self.btn_prediction_cancel.setObjectName("btn_prediction_cancel")
        self.horizontalLayout_18.addWidget(self.btn_prediction_cancel)
        self.btn_prediction_start = QtWidgets.QPushButton(self.tab_6)
        self.btn_prediction_start.setObjectName("btn_prediction_start")
        self.horizontalLayout_18.addWidget(self.btn_prediction_start)
        self.verticalLayout_13.addLayout(self.horizontalLayout_18)
        self.progress_bar_prediction = QtWidgets.QProgressBar(self.tab_6)
        self.progress_bar_prediction.setProperty("value", 24)
        self.progress_bar_prediction.setObjectName("progress_bar_prediction")
        self.verticalLayout_13.addWidget(self.progress_bar_prediction)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.Home_3 = QtWidgets.QWidget()
        self.Home_3.setEnabled(True)
        self.Home_3.setObjectName("Home_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Home_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.Home_3)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.txt_analysis_project_name = QtWidgets.QLineEdit(self.tab_3)
        self.txt_analysis_project_name.setObjectName("txt_analysis_project_name")
        self.verticalLayout_2.addWidget(self.txt_analysis_project_name)
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_2.addWidget(self.label_20)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.txt_analysis_load_reference = QtWidgets.QLineEdit(self.tab_3)
        self.txt_analysis_load_reference.setObjectName("txt_analysis_load_reference")
        self.horizontalLayout_19.addWidget(self.txt_analysis_load_reference)
        self.btn_analysis_load_reference = QtWidgets.QToolButton(self.tab_3)
        self.btn_analysis_load_reference.setObjectName("btn_analysis_load_reference")
        self.horizontalLayout_19.addWidget(self.btn_analysis_load_reference)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_analysis_load_model = QtWidgets.QPushButton(self.tab_3)
        self.btn_analysis_load_model.setMinimumSize(QtCore.QSize(180, 0))
        self.btn_analysis_load_model.setObjectName("btn_analysis_load_model")
        self.horizontalLayout_4.addWidget(self.btn_analysis_load_model)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.txt_analysis_load_model = QtWidgets.QTextEdit(self.tab_3)
        self.txt_analysis_load_model.setEnabled(False)
        self.txt_analysis_load_model.setMaximumSize(QtCore.QSize(16777215, 40))
        self.txt_analysis_load_model.setObjectName("txt_analysis_load_model")
        self.verticalLayout_2.addWidget(self.txt_analysis_load_model)
        self.cb_analysis_chain_info = QtWidgets.QCheckBox(self.tab_3)
        self.cb_analysis_chain_info.setObjectName("cb_analysis_chain_info")
        self.verticalLayout_2.addWidget(self.cb_analysis_chain_info)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.txt_analysis_chain_ref = QtWidgets.QLineEdit(self.tab_3)
        self.txt_analysis_chain_ref.setObjectName("txt_analysis_chain_ref")
        self.verticalLayout.addWidget(self.txt_analysis_chain_ref)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.txt_analysis_chain_model = QtWidgets.QLineEdit(self.tab_3)
        self.txt_analysis_chain_model.setObjectName("txt_analysis_chain_model")
        self.verticalLayout.addWidget(self.txt_analysis_chain_model)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 152, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.btn_analysis_start = QtWidgets.QPushButton(self.tab_3)
        self.btn_analysis_start.setObjectName("btn_analysis_start")
        self.horizontalLayout_2.addWidget(self.btn_analysis_start)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.progress_bar_analysis = QtWidgets.QProgressBar(self.tab_3)
        self.progress_bar_analysis.setProperty("value", 24)
        self.progress_bar_analysis.setObjectName("progress_bar_analysis")
        self.verticalLayout_2.addWidget(self.progress_bar_analysis)
        self.tabWidget_3.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_21 = QtWidgets.QLabel(self.tab_5)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_12.addWidget(self.label_21)
        self.txt_batch_job_name = QtWidgets.QLineEdit(self.tab_5)
        self.txt_batch_job_name.setObjectName("txt_batch_job_name")
        self.verticalLayout_12.addWidget(self.txt_batch_job_name)
        self.label_22 = QtWidgets.QLabel(self.tab_5)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_12.addWidget(self.label_22)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.txt_batch_load_reference = QtWidgets.QLineEdit(self.tab_5)
        self.txt_batch_load_reference.setObjectName("txt_batch_load_reference")
        self.horizontalLayout_20.addWidget(self.txt_batch_load_reference)
        self.btn_batch_load_reference = QtWidgets.QToolButton(self.tab_5)
        self.btn_batch_load_reference.setObjectName("btn_batch_load_reference")
        self.horizontalLayout_20.addWidget(self.btn_batch_load_reference)
        self.verticalLayout_12.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.btn_batch_load_model = QtWidgets.QPushButton(self.tab_5)
        self.btn_batch_load_model.setMinimumSize(QtCore.QSize(180, 0))
        self.btn_batch_load_model.setObjectName("btn_batch_load_model")
        self.horizontalLayout_15.addWidget(self.btn_batch_load_model)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        self.txt_batch_load_model = QtWidgets.QTextEdit(self.tab_5)
        self.txt_batch_load_model.setEnabled(False)
        self.txt_batch_load_model.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txt_batch_load_model.setObjectName("txt_batch_load_model")
        self.verticalLayout_12.addWidget(self.txt_batch_load_model)
        self.cb_batch_chain_info = QtWidgets.QCheckBox(self.tab_5)
        self.cb_batch_chain_info.setObjectName("cb_batch_chain_info")
        self.verticalLayout_12.addWidget(self.cb_batch_chain_info)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_11.addWidget(self.label_11)
        self.txt_batch_chain_ref = QtWidgets.QLineEdit(self.tab_5)
        self.txt_batch_chain_ref.setObjectName("txt_batch_chain_ref")
        self.verticalLayout_11.addWidget(self.txt_batch_chain_ref)
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.txt_batch_chain_model = QtWidgets.QLineEdit(self.tab_5)
        self.txt_batch_chain_model.setObjectName("txt_batch_chain_model")
        self.verticalLayout_11.addWidget(self.txt_batch_chain_model)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem5)
        self.btn_batch_start = QtWidgets.QPushButton(self.tab_5)
        self.btn_batch_start.setObjectName("btn_batch_start")
        self.horizontalLayout_16.addWidget(self.btn_batch_start)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.progress_bar_batch = QtWidgets.QProgressBar(self.tab_5)
        self.progress_bar_batch.setProperty("value", 24)
        self.progress_bar_batch.setObjectName("progress_bar_batch")
        self.verticalLayout_12.addWidget(self.progress_bar_batch)
        self.tabWidget_3.addTab(self.tab_5, "")
        self.verticalLayout_10.addWidget(self.tabWidget_3)
        self.tabWidget_2.addTab(self.Home_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_view_distance_plot = QtWidgets.QPushButton(self.tab_4)
        self.btn_view_distance_plot.setObjectName("btn_view_distance_plot")
        self.horizontalLayout_10.addWidget(self.btn_view_distance_plot)
        self.btn_view_struct_alignment = QtWidgets.QPushButton(self.tab_4)
        self.btn_view_struct_alignment.setObjectName("btn_view_struct_alignment")
        self.horizontalLayout_10.addWidget(self.btn_view_struct_alignment)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btn_view_distance_histogram = QtWidgets.QPushButton(self.tab_4)
        self.btn_view_distance_histogram.setObjectName("btn_view_distance_histogram")
        self.horizontalLayout_11.addWidget(self.btn_view_distance_histogram)
        self.btn_view_distance_table = QtWidgets.QPushButton(self.tab_4)
        self.btn_view_distance_table.setObjectName("btn_view_distance_table")
        self.horizontalLayout_11.addWidget(self.btn_view_distance_table)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cb_interesting_regions = QtWidgets.QComboBox(self.tab_4)
        self.cb_interesting_regions.setObjectName("cb_interesting_regions")
        self.verticalLayout_5.addWidget(self.cb_interesting_regions)
        self.btn_view_interesting_region = QtWidgets.QPushButton(self.tab_4)
        self.btn_view_interesting_region.setObjectName("btn_view_interesting_region")
        self.verticalLayout_5.addWidget(self.btn_view_interesting_region)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.project_list = QtWidgets.QListWidget(self.tab_4)
        self.project_list.setObjectName("project_list")
        self.verticalLayout_3.addWidget(self.project_list)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 240, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.Image = QtWidgets.QWidget()
        self.Image.setObjectName("Image")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Image)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_2 = QtWidgets.QLabel(self.Image)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_13.addWidget(self.label_2)
        self.box_representation = QtWidgets.QComboBox(self.Image)
        self.box_representation.setObjectName("box_representation")
        self.horizontalLayout_13.addWidget(self.box_representation)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.Image)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.box_bg_color = QtWidgets.QComboBox(self.Image)
        self.box_bg_color.setObjectName("box_bg_color")
        self.horizontalLayout_6.addWidget(self.box_bg_color)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.Image)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.box_renderer = QtWidgets.QComboBox(self.Image)
        self.box_renderer.setObjectName("box_renderer")
        self.horizontalLayout_7.addWidget(self.box_renderer)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.Image)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.box_ray_trace_mode = QtWidgets.QComboBox(self.Image)
        self.box_ray_trace_mode.setObjectName("box_ray_trace_mode")
        self.horizontalLayout_5.addWidget(self.box_ray_trace_mode)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_14 = QtWidgets.QLabel(self.Image)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.box_ray_texture = QtWidgets.QComboBox(self.Image)
        self.box_ray_texture.setObjectName("box_ray_texture")
        self.horizontalLayout.addWidget(self.box_ray_texture)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.Image)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.cb_ray_tracing = QtWidgets.QCheckBox(self.Image)
        self.cb_ray_tracing.setText("")
        self.cb_ray_tracing.setObjectName("cb_ray_tracing")
        self.horizontalLayout_8.addWidget(self.cb_ray_tracing)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.Image)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.cb_transparent_bg = QtWidgets.QCheckBox(self.Image)
        self.cb_transparent_bg.setText("")
        self.cb_transparent_bg.setObjectName("cb_transparent_bg")
        self.horizontalLayout_9.addWidget(self.cb_transparent_bg)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        spacerItem7 = QtWidgets.QSpacerItem(20, 238, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_save_scene = QtWidgets.QPushButton(self.Image)
        self.btn_save_scene.setObjectName("btn_save_scene")
        self.verticalLayout_8.addWidget(self.btn_save_scene)
        self.btn_update_scene = QtWidgets.QPushButton(self.Image)
        self.btn_update_scene.setObjectName("btn_update_scene")
        self.verticalLayout_8.addWidget(self.btn_update_scene)
        self.btn_preview_image = QtWidgets.QPushButton(self.Image)
        self.btn_preview_image.setObjectName("btn_preview_image")
        self.verticalLayout_8.addWidget(self.btn_preview_image)
        self.btn_save_image = QtWidgets.QPushButton(self.Image)
        self.btn_save_image.setObjectName("btn_save_image")
        self.verticalLayout_8.addWidget(self.btn_save_image)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.tabWidget_2.addTab(self.Image, "")
        self.verticalLayout_4.addWidget(self.tabWidget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuWizard = QtWidgets.QMenu(self.menubar)
        self.menuWizard.setObjectName("menuWizard")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuDisplay = QtWidgets.QMenu(self.menubar)
        self.menuDisplay.setObjectName("menuDisplay")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_file_open = QtWidgets.QAction(MainWindow)
        self.action_file_open.setCheckable(False)
        self.action_file_open.setShortcut("")
        self.action_file_open.setObjectName("action_file_open")
        self.action_file_save_as = QtWidgets.QAction(MainWindow)
        self.action_file_save_as.setObjectName("action_file_save_as")
        self.action_file_save = QtWidgets.QAction(MainWindow)
        self.action_file_save.setObjectName("action_file_save")
        self.action_wizard_prepare_model_pdbs = QtWidgets.QAction(MainWindow)
        self.action_wizard_prepare_model_pdbs.setObjectName("action_wizard_prepare_model_pdbs")
        self.actSettingsPdbPreparation = QtWidgets.QAction(MainWindow)
        self.actSettingsPdbPreparation.setObjectName("actSettingsPdbPreparation")
        self.action_file_quit = QtWidgets.QAction(MainWindow)
        self.action_file_quit.setObjectName("action_file_quit")
        self.action_help_docs = QtWidgets.QAction(MainWindow)
        self.action_help_docs.setObjectName("action_help_docs")
        self.action_help_about = QtWidgets.QAction(MainWindow)
        self.action_help_about.setObjectName("action_help_about")
        self.action_settings_edit_all = QtWidgets.QAction(MainWindow)
        self.action_settings_edit_all.setObjectName("action_settings_edit_all")
        self.action_settings_change_workspace = QtWidgets.QAction(MainWindow)
        self.action_settings_change_workspace.setObjectName("action_settings_change_workspace")
        self.action_file_restore_settings = QtWidgets.QAction(MainWindow)
        self.action_file_restore_settings.setObjectName("action_file_restore_settings")
        self.action_settings_model_w_off_colab_notebook = QtWidgets.QAction(MainWindow)
        self.action_settings_model_w_off_colab_notebook.setCheckable(True)
        self.action_settings_model_w_off_colab_notebook.setObjectName("action_settings_model_w_off_colab_notebook")
        self.action_display_current_workspace = QtWidgets.QAction(MainWindow)
        self.action_display_current_workspace.setObjectName("action_display_current_workspace")
        self.action_display_project_path = QtWidgets.QAction(MainWindow)
        self.action_display_project_path.setObjectName("action_display_project_path")
        self.action_help_docs_pdf = QtWidgets.QAction(MainWindow)
        self.action_help_docs_pdf.setObjectName("action_help_docs_pdf")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_file_open)
        self.menuFile.addAction(self.action_file_save_as)
        self.menuFile.addAction(self.action_file_save)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_file_restore_settings)
        self.menuFile.addAction(self.action_file_quit)
        self.menuSettings.addAction(self.action_settings_edit_all)
        self.menuSettings.addAction(self.action_settings_model_w_off_colab_notebook)
        self.menuWizard.addAction(self.action_wizard_prepare_model_pdbs)
        self.menuHelp.addAction(self.action_help_docs)
        self.menuHelp.addAction(self.action_help_docs_pdf)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.action_help_about)
        self.menuDisplay.addAction(self.action_display_current_workspace)
        self.menuDisplay.addAction(self.action_display_project_path)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWizard.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_18.setText(_translate("MainWindow", "Enter a project name:"))
        self.label_15.setText(_translate("MainWindow", "Choose a .pdb file or enter a PDB ID:"))
        self.btn_prediction_load_reference.setText(_translate("MainWindow", "..."))
        self.cb_prediction_chain_info.setText(_translate("MainWindow", "Add chain information"))
        self.label_16.setText(_translate("MainWindow", "Chains in reference (input style: G,H)"))
        self.label_17.setText(_translate("MainWindow", "Chains in models (input style: A,B)"))
        self.btn_prediction_cancel.setText(_translate("MainWindow", "Cancel"))
        self.btn_prediction_start.setText(_translate("MainWindow", "Predict with Colab Notebook"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Prediction + Analysis"))
        self.label_19.setText(_translate("MainWindow", "Enter a project name:"))
        self.label_20.setText(_translate("MainWindow", "Choose a .pdb file or enter a PDB ID:"))
        self.btn_analysis_load_reference.setText(_translate("MainWindow", "..."))
        self.btn_analysis_load_model.setText(_translate("MainWindow", "Open model"))
        self.cb_analysis_chain_info.setText(_translate("MainWindow", "Add chain information"))
        self.label_4.setText(_translate("MainWindow", "Chains in reference (input style: G,H)"))
        self.label_5.setText(_translate("MainWindow", "Chains in models (input style: A,B)"))
        self.label.setText(_translate("MainWindow", "Start structure prediction analysis"))
        self.btn_analysis_start.setText(_translate("MainWindow", "Start"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3), _translate("MainWindow", "Single Analysis"))
        self.label_21.setText(_translate("MainWindow", "Enter a job name:"))
        self.label_22.setText(_translate("MainWindow", "Choose a .pdb file or enter a PDB ID:"))
        self.btn_batch_load_reference.setText(_translate("MainWindow", "..."))
        self.btn_batch_load_model.setText(_translate("MainWindow", "Open models"))
        self.cb_batch_chain_info.setText(_translate("MainWindow", "Add chain information"))
        self.label_11.setText(_translate("MainWindow", "Chains in reference (input style: G,H)"))
        self.label_12.setText(_translate("MainWindow", "Chains in models (input style: A,B)"))
        self.label_13.setText(_translate("MainWindow", "Start batch analysis"))
        self.btn_batch_start.setText(_translate("MainWindow", "Start"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("MainWindow", "Batch"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Home_3), _translate("MainWindow", "Analysis"))
        self.btn_view_distance_plot.setText(_translate("MainWindow", "View distance plot"))
        self.btn_view_struct_alignment.setText(_translate("MainWindow", "View structure alignment"))
        self.btn_view_distance_histogram.setText(_translate("MainWindow", "View distance histogram"))
        self.btn_view_distance_table.setText(_translate("MainWindow", "View distance table"))
        self.btn_view_interesting_region.setText(_translate("MainWindow", "View interesting region"))
        self.label_9.setText(_translate("MainWindow", "Project List:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Results"))
        self.label_2.setText(_translate("MainWindow", "Representation"))
        self.label_3.setText(_translate("MainWindow", "Background Color"))
        self.label_7.setText(_translate("MainWindow", "Renderer"))
        self.label_10.setText(_translate("MainWindow", "Ray-Trace-Mode"))
        self.label_14.setText(_translate("MainWindow", "Ray Texture"))
        self.label_6.setText(_translate("MainWindow", "Ray-Tracing"))
        self.label_8.setText(_translate("MainWindow", "Transparent Background"))
        self.btn_save_scene.setText(_translate("MainWindow", "Save Scene"))
        self.btn_update_scene.setText(_translate("MainWindow", "Update Scene"))
        self.btn_preview_image.setText(_translate("MainWindow", "Preview Image"))
        self.btn_save_image.setText(_translate("MainWindow", "Save Image"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Image), _translate("MainWindow", "Image"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuSettings.setTitle(_translate("MainWindow", "&Settings"))
        self.menuWizard.setTitle(_translate("MainWindow", "&Wizard"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.menuDisplay.setTitle(_translate("MainWindow", "&Display"))
        self.action_file_open.setText(_translate("MainWindow", "&Open"))
        self.action_file_save_as.setText(_translate("MainWindow", "&Save as"))
        self.action_file_save.setText(_translate("MainWindow", "Save"))
        self.action_wizard_prepare_model_pdbs.setText(_translate("MainWindow", "Prepare Models"))
        self.actSettingsPdbPreparation.setText(_translate("MainWindow", "pdb Preparation"))
        self.action_file_quit.setText(_translate("MainWindow", "&Quit"))
        self.action_help_docs.setText(_translate("MainWindow", "&Documentation"))
        self.action_help_about.setText(_translate("MainWindow", "&About"))
        self.action_settings_edit_all.setText(_translate("MainWindow", "&Edit all"))
        self.action_settings_change_workspace.setText(_translate("MainWindow", "Change Workspace"))
        self.action_file_restore_settings.setText(_translate("MainWindow", "Restore Settings"))
        self.action_settings_model_w_off_colab_notebook.setText(_translate("MainWindow", "Modeling with \"official\" colab notebook"))
        self.action_display_current_workspace.setText(_translate("MainWindow", "Current &Workspace Path"))
        self.action_display_project_path.setText(_translate("MainWindow", "Current &Project Path"))
        self.action_help_docs_pdf.setText(_translate("MainWindow", "Documentation P&DF"))

