# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pyssa\gui\ui\forms\add_protein_pair_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):

  def setupUi(self, Dialog):
    Dialog.setObjectName("Dialog")
    Dialog.resize(520, 630)
    self.verticalLayout_6 = QtWidgets.QVBoxLayout(Dialog)
    self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout_6.setObjectName("verticalLayout_6")
    self.frame = QtWidgets.QFrame(Dialog)
    self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
    self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
    self.frame.setObjectName("frame")
    self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
    self.verticalLayout_5.setObjectName("verticalLayout_5")
    self.verticalLayout_4 = QtWidgets.QVBoxLayout()
    self.verticalLayout_4.setObjectName("verticalLayout_4")
    self.verticalLayout = QtWidgets.QVBoxLayout()
    self.verticalLayout.setObjectName("verticalLayout")
    self.lbl_prot_1 = QtWidgets.QLabel(self.frame)
    self.lbl_prot_1.setObjectName("lbl_prot_1")
    self.verticalLayout.addWidget(self.lbl_prot_1)
    self.tree_prot_1 = QtWidgets.QTreeView(self.frame)
    self.tree_prot_1.setObjectName("tree_prot_1")
    self.verticalLayout.addWidget(self.tree_prot_1)
    self.verticalLayout_4.addLayout(self.verticalLayout)
    self.horizontalLayout = QtWidgets.QHBoxLayout()
    self.horizontalLayout.setObjectName("horizontalLayout")
    spacerItem = QtWidgets.QSpacerItem(
        40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
    )
    self.horizontalLayout.addItem(spacerItem)
    self.btn_next = QtWidgets.QPushButton(self.frame)
    self.btn_next.setObjectName("btn_next")
    self.horizontalLayout.addWidget(self.btn_next)
    self.verticalLayout_4.addLayout(self.horizontalLayout)
    self.verticalLayout_5.addLayout(self.verticalLayout_4)
    self.verticalLayout_2 = QtWidgets.QVBoxLayout()
    self.verticalLayout_2.setObjectName("verticalLayout_2")
    self.lbl_prot_2 = QtWidgets.QLabel(self.frame)
    self.lbl_prot_2.setObjectName("lbl_prot_2")
    self.verticalLayout_2.addWidget(self.lbl_prot_2)
    self.tree_prot_2 = QtWidgets.QTreeView(self.frame)
    self.tree_prot_2.setObjectName("tree_prot_2")
    self.verticalLayout_2.addWidget(self.tree_prot_2)
    self.verticalLayout_5.addLayout(self.verticalLayout_2)
    self.verticalLayout_6.addWidget(self.frame)
    spacerItem1 = QtWidgets.QSpacerItem(
        20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
    )
    self.verticalLayout_6.addItem(spacerItem1)
    self.frame_bottom = QtWidgets.QFrame(Dialog)
    self.frame_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
    self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
    self.frame_bottom.setObjectName("frame_bottom")
    self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_bottom)
    self.verticalLayout_3.setObjectName("verticalLayout_3")
    self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_2.setObjectName("horizontalLayout_2")
    spacerItem2 = QtWidgets.QSpacerItem(
        40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
    )
    self.horizontalLayout_2.addItem(spacerItem2)
    self.btn_back = QtWidgets.QPushButton(self.frame_bottom)
    self.btn_back.setObjectName("btn_back")
    self.horizontalLayout_2.addWidget(self.btn_back)
    self.btn_add = QtWidgets.QPushButton(self.frame_bottom)
    self.btn_add.setObjectName("btn_add")
    self.horizontalLayout_2.addWidget(self.btn_add)
    self.btn_cancel = QtWidgets.QPushButton(self.frame_bottom)
    self.btn_cancel.setObjectName("btn_cancel")
    self.horizontalLayout_2.addWidget(self.btn_cancel)
    self.verticalLayout_3.addLayout(self.horizontalLayout_2)
    self.verticalLayout_6.addWidget(self.frame_bottom)

    self.retranslateUi(Dialog)
    QtCore.QMetaObject.connectSlotsByName(Dialog)

  def retranslateUi(self, Dialog):
    _translate = QtCore.QCoreApplication.translate
    Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
    self.lbl_prot_1.setText(
        _translate("Dialog", "Select first protein structure")
    )
    self.btn_next.setText(_translate("Dialog", "Next"))
    self.lbl_prot_2.setText(
        _translate("Dialog", "Select second protein structure")
    )
    self.btn_back.setText(_translate("Dialog", "Back"))
    self.btn_add.setText(_translate("Dialog", "Add"))
    self.btn_cancel.setText(_translate("Dialog", "Cancel"))
