# Form implementation generated from reading ui file 'src/pyssa/gui/ui/forms/rename_object_view.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(473, 143)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_description = QtWidgets.QLabel(parent=self.frame)
        self.lbl_description.setObjectName("lbl_description")
        self.verticalLayout_2.addWidget(self.lbl_description)
        self.le_name = QtWidgets.QLineEdit(parent=self.frame)
        self.le_name.setObjectName("le_name")
        self.verticalLayout_2.addWidget(self.le_name)
        self.lbl_status = QtWidgets.QLabel(parent=self.frame)
        self.lbl_status.setObjectName("lbl_status")
        self.verticalLayout_2.addWidget(self.lbl_status)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.frame_bottom = QtWidgets.QFrame(parent=Dialog)
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_bottom)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_rename = QtWidgets.QPushButton(parent=self.frame_bottom)
        self.btn_rename.setObjectName("btn_rename")
        self.horizontalLayout.addWidget(self.btn_rename)
        self.btn_cancel = QtWidgets.QPushButton(parent=self.frame_bottom)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.frame_bottom)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_description.setText(_translate("Dialog", "Enter a new name"))
        self.lbl_status.setText(_translate("Dialog", "Status"))
        self.btn_rename.setText(_translate("Dialog", "Rename"))
        self.btn_cancel.setText(_translate("Dialog", "Cancel"))
