# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pyssa\gui\ui\forms\distance_analysis_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):

  def setupUi(self, Dialog):
    Dialog.setObjectName("Dialog")
    Dialog.resize(463, 785)
    self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
    self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout_2.setObjectName("verticalLayout_2")
    self.frame_main = QtWidgets.QFrame(Dialog)
    self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
    self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
    self.frame_main.setObjectName("frame_main")
    self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_main)
    self.verticalLayout.setObjectName("verticalLayout")
    self.verticalLayout_45 = QtWidgets.QVBoxLayout()
    self.verticalLayout_45.setObjectName("verticalLayout_45")
    self.lbl_distance_analysis_overview = QtWidgets.QLabel(self.frame_main)
    self.lbl_distance_analysis_overview.setObjectName(
        "lbl_distance_analysis_overview"
    )
    self.verticalLayout_45.addWidget(self.lbl_distance_analysis_overview)
    self.list_distance_analysis_overview = QtWidgets.QListWidget(
        self.frame_main
    )
    sizePolicy = QtWidgets.QSizePolicy(
        QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
    )
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(
        self.list_distance_analysis_overview.sizePolicy().hasHeightForWidth()
    )
    self.list_distance_analysis_overview.setSizePolicy(sizePolicy)
    self.list_distance_analysis_overview.setMinimumSize(QtCore.QSize(0, 0))
    self.list_distance_analysis_overview.setMaximumSize(
        QtCore.QSize(16777215, 16777215)
    )
    self.list_distance_analysis_overview.setObjectName(
        "list_distance_analysis_overview"
    )
    self.verticalLayout_45.addWidget(self.list_distance_analysis_overview)
    self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_21.setObjectName("horizontalLayout_21")
    spacerItem = QtWidgets.QSpacerItem(
        40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
    )
    self.horizontalLayout_21.addItem(spacerItem)
    self.btn_distance_analysis_remove = QtWidgets.QPushButton(self.frame_main)
    self.btn_distance_analysis_remove.setObjectName(
        "btn_distance_analysis_remove"
    )
    self.horizontalLayout_21.addWidget(self.btn_distance_analysis_remove)
    self.btn_distance_analysis_add = QtWidgets.QPushButton(self.frame_main)
    self.btn_distance_analysis_add.setObjectName("btn_distance_analysis_add")
    self.horizontalLayout_21.addWidget(self.btn_distance_analysis_add)
    self.verticalLayout_45.addLayout(self.horizontalLayout_21)
    self.verticalLayout.addLayout(self.verticalLayout_45)
    self.verticalLayout_2.addWidget(self.frame_main)
    spacerItem1 = QtWidgets.QSpacerItem(
        17, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
    )
    self.verticalLayout_2.addItem(spacerItem1)
    self.frame_bottom = QtWidgets.QFrame(Dialog)
    self.frame_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
    self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
    self.frame_bottom.setObjectName("frame_bottom")
    self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_bottom)
    self.horizontalLayout_2.setObjectName("horizontalLayout_2")
    self.horizontalLayout = QtWidgets.QHBoxLayout()
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.btn_help = QtWidgets.QPushButton(self.frame_bottom)
    self.btn_help.setObjectName("btn_help")
    self.horizontalLayout.addWidget(self.btn_help)
    spacerItem2 = QtWidgets.QSpacerItem(
        40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
    )
    self.horizontalLayout.addItem(spacerItem2)
    self.btn_distance_analysis_start = QtWidgets.QPushButton(self.frame_bottom)
    self.btn_distance_analysis_start.setObjectName(
        "btn_distance_analysis_start"
    )
    self.horizontalLayout.addWidget(self.btn_distance_analysis_start)
    self.btn_cancel = QtWidgets.QPushButton(self.frame_bottom)
    self.btn_cancel.setObjectName("btn_cancel")
    self.horizontalLayout.addWidget(self.btn_cancel)
    self.horizontalLayout_2.addLayout(self.horizontalLayout)
    self.verticalLayout_2.addWidget(self.frame_bottom)

    self.retranslateUi(Dialog)
    QtCore.QMetaObject.connectSlotsByName(Dialog)

  def retranslateUi(self, Dialog):
    _translate = QtCore.QCoreApplication.translate
    Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
    self.lbl_distance_analysis_overview.setText(
        _translate("Dialog", "Protein structure analysis'")
    )
    self.btn_distance_analysis_remove.setText(_translate("Dialog", "Remove"))
    self.btn_distance_analysis_add.setText(_translate("Dialog", "Add"))
    self.btn_help.setText(_translate("Dialog", "Help"))
    self.btn_distance_analysis_start.setText(_translate("Dialog", "Start"))
    self.btn_cancel.setText(_translate("Dialog", "Cancel"))
