# Form implementation generated from reading ui file '.\welcome_screen_view.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(536, 334)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_pyssa_icon = QtWidgets.QLabel(parent=self.frame)
        self.lbl_pyssa_icon.setObjectName("lbl_pyssa_icon")
        self.horizontalLayout_2.addWidget(self.lbl_pyssa_icon)
        self.lbl_welcome = QtWidgets.QLabel(parent=self.frame)
        self.lbl_welcome.setObjectName("lbl_welcome")
        self.horizontalLayout_2.addWidget(self.lbl_welcome)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.projects_list_view = QtWidgets.QListView(parent=self.frame)
        self.projects_list_view.setObjectName("projects_list_view")
        self.verticalLayout.addWidget(self.projects_list_view)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addWidget(self.frame)
        self.frame_bottom = QtWidgets.QFrame(parent=Dialog)
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_bottom)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_help = QtWidgets.QPushButton(parent=self.frame_bottom)
        self.btn_help.setObjectName("btn_help")
        self.horizontalLayout.addWidget(self.btn_help)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_new_project = QtWidgets.QPushButton(parent=self.frame_bottom)
        self.btn_new_project.setObjectName("btn_new_project")
        self.horizontalLayout.addWidget(self.btn_new_project)
        self.btn_open_project = QtWidgets.QPushButton(parent=self.frame_bottom)
        self.btn_open_project.setObjectName("btn_open_project")
        self.horizontalLayout.addWidget(self.btn_open_project)
        self.btn_close = QtWidgets.QPushButton(parent=self.frame_bottom)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.frame_bottom)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_pyssa_icon.setText(_translate("Dialog", "TextLabel"))
        self.lbl_welcome.setText(_translate("Dialog", "Welcome to PySSA"))
        self.label.setText(_translate("Dialog", "Projects"))
        self.btn_help.setText(_translate("Dialog", "Help"))
        self.btn_new_project.setText(_translate("Dialog", "New"))
        self.btn_open_project.setText(_translate("Dialog", "Open"))
        self.btn_close.setText(_translate("Dialog", "Close"))
