# Form implementation generated from reading ui file '.\src\python\pydd\components\internal\core\gui\forms\create_project_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(356, 161)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_description = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_description.setFont(font)
        self.lbl_description.setObjectName("lbl_description")
        self.horizontalLayout.addWidget(self.lbl_description)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.txt_project_name = QtWidgets.QLineEdit(parent=self.frame)
        self.txt_project_name.setObjectName("txt_project_name")
        self.verticalLayout.addWidget(self.txt_project_name)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.frame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 251, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.frame_bottom = QtWidgets.QFrame(parent=Dialog)
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_bottom)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_help = QtWidgets.QPushButton(parent=self.frame_bottom)
        self.btn_help.setObjectName("btn_help")
        self.horizontalLayout_2.addWidget(self.btn_help)
        spacerItem2 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_create = QtWidgets.QPushButton(parent=self.frame_bottom)
        self.btn_create.setObjectName("btn_create")
        self.horizontalLayout_2.addWidget(self.btn_create)
        self.btn_cancel = QtWidgets.QPushButton(parent=self.frame_bottom)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        self.verticalLayout_3.addWidget(self.frame_bottom)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_description.setText(_translate("Dialog", "Create New Project"))
        self.label_2.setText(_translate("Dialog", "Project Name"))
        self.btn_help.setText(_translate("Dialog", "Help"))
        self.btn_create.setText(_translate("Dialog", "Create"))
        self.btn_cancel.setText(_translate("Dialog", "Cancel"))
