# Form implementation generated from reading ui file '.\src\python\pydd\components\internal\import_ligand\gui\forms\dialog_preview_import_ligand.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(463, 465)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scroll_area_molecules = QtWidgets.QScrollArea(parent=self.frame)
        self.scroll_area_molecules.setWidgetResizable(True)
        self.scroll_area_molecules.setObjectName("scroll_area_molecules")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 441, 392))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_area_molecules.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scroll_area_molecules)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_bottom = QtWidgets.QFrame(parent=Dialog)
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_bottom)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_help = QtWidgets.QPushButton(parent=self.frame_bottom)
        self.btn_help.setObjectName("btn_help")
        self.horizontalLayout.addWidget(self.btn_help)
        spacerItem = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_import = QtWidgets.QPushButton(parent=self.frame_bottom)
        self.btn_import.setMinimumSize(QtCore.QSize(131, 0))
        self.btn_import.setObjectName("btn_import")
        self.horizontalLayout.addWidget(self.btn_import)
        self.btn_cancel = QtWidgets.QPushButton(parent=self.frame_bottom)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.frame_bottom)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_help.setText(_translate("Dialog", "Help"))
        self.btn_import.setText(_translate("Dialog", "Import"))
        self.btn_cancel.setText(_translate("Dialog", "Cancel"))
