# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dlgSequenceViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):

  def setupUi(self, Dialog):
    Dialog.setObjectName("Dialog")
    Dialog.resize(568, 322)
    self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
    self.verticalLayout_2.setObjectName("verticalLayout_2")
    self.verticalLayout = QtWidgets.QVBoxLayout()
    self.verticalLayout.setObjectName("verticalLayout")
    self.lbl_seq_viewer = QtWidgets.QLabel(Dialog)
    self.lbl_seq_viewer.setObjectName("lbl_seq_viewer")
    self.verticalLayout.addWidget(self.lbl_seq_viewer)
    self.table_seq_viewer = QtWidgets.QTableWidget(Dialog)
    self.table_seq_viewer.setObjectName("table_seq_viewer")
    self.table_seq_viewer.setColumnCount(0)
    self.table_seq_viewer.setRowCount(0)
    self.verticalLayout.addWidget(self.table_seq_viewer)
    self.verticalLayout_2.addLayout(self.verticalLayout)
    self.horizontalLayout = QtWidgets.QHBoxLayout()
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.lbl_duplicate_seq = QtWidgets.QLabel(Dialog)
    self.lbl_duplicate_seq.setObjectName("lbl_duplicate_seq")
    self.horizontalLayout.addWidget(self.lbl_duplicate_seq)
    self.btn_duplicate_seq = QtWidgets.QPushButton(Dialog)
    self.btn_duplicate_seq.setMaximumSize(QtCore.QSize(131, 16777215))
    self.btn_duplicate_seq.setObjectName("btn_duplicate_seq")
    self.horizontalLayout.addWidget(self.btn_duplicate_seq)
    self.verticalLayout_2.addLayout(self.horizontalLayout)
    self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_2.setObjectName("horizontalLayout_2")
    self.lbl_remove_seq = QtWidgets.QLabel(Dialog)
    self.lbl_remove_seq.setObjectName("lbl_remove_seq")
    self.horizontalLayout_2.addWidget(self.lbl_remove_seq)
    self.btn_remove_seq = QtWidgets.QPushButton(Dialog)
    self.btn_remove_seq.setMaximumSize(QtCore.QSize(131, 16777215))
    self.btn_remove_seq.setObjectName("btn_remove_seq")
    self.horizontalLayout_2.addWidget(self.btn_remove_seq)
    self.verticalLayout_2.addLayout(self.horizontalLayout_2)

    self.retranslateUi(Dialog)
    QtCore.QMetaObject.connectSlotsByName(Dialog)

  def retranslateUi(self, Dialog):
    _translate = QtCore.QCoreApplication.translate
    Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
    self.lbl_seq_viewer.setText(_translate("Dialog", "Sequence alignment"))
    self.lbl_duplicate_seq.setText(_translate("Dialog", "Selected sequence"))
    self.btn_duplicate_seq.setText(_translate("Dialog", "Duplicate"))
    self.lbl_remove_seq.setText(_translate("Dialog", "Selected sequence"))
    self.btn_remove_seq.setText(_translate("Dialog", "Remove"))
