# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pyssa\gui\ui\forms\hotspots_protein_regions_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(339, 255)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_sticks_show = QtWidgets.QPushButton(Dialog)
        self.btn_sticks_show.setObjectName("btn_sticks_show")
        self.horizontalLayout.addWidget(self.btn_sticks_show)
        self.btn_sticks_hide = QtWidgets.QPushButton(Dialog)
        self.btn_sticks_hide.setObjectName("btn_sticks_hide")
        self.horizontalLayout.addWidget(self.btn_sticks_hide)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.cb_disulfide_bonds = QtWidgets.QComboBox(Dialog)
        self.cb_disulfide_bonds.setObjectName("cb_disulfide_bonds")
        self.cb_disulfide_bonds.addItem("")
        self.cb_disulfide_bonds.addItem("")
        self.horizontalLayout_3.addWidget(self.cb_disulfide_bonds)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.btn_position_zoom = QtWidgets.QPushButton(Dialog)
        self.btn_position_zoom.setObjectName("btn_position_zoom")
        self.horizontalLayout_4.addWidget(self.btn_position_zoom)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_info = QtWidgets.QPushButton(Dialog)
        self.btn_info.setObjectName("btn_info")
        self.horizontalLayout_2.addWidget(self.btn_info)
        spacerItem4 = QtWidgets.QSpacerItem(628, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Sticks"))
        self.btn_sticks_show.setText(_translate("Dialog", "Show"))
        self.btn_sticks_hide.setText(_translate("Dialog", "Hide"))
        self.label_4.setText(_translate("Dialog", "Disulfide Bonds"))
        self.cb_disulfide_bonds.setItemText(0, _translate("Dialog", "Hide"))
        self.cb_disulfide_bonds.setItemText(1, _translate("Dialog", "Show"))
        self.label_3.setText(_translate("Dialog", "Region"))
        self.btn_position_zoom.setText(_translate("Dialog", "Zoom"))
        self.btn_info.setText(_translate("Dialog", "Info"))
