# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_sequence_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(457, 542)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_seq_name = QtWidgets.QLabel(Dialog)
        self.lbl_seq_name.setObjectName("lbl_seq_name")
        self.verticalLayout.addWidget(self.lbl_seq_name)
        self.le_seq_name = QtWidgets.QLineEdit(Dialog)
        self.le_seq_name.setObjectName("le_seq_name")
        self.verticalLayout.addWidget(self.le_seq_name)
        self.lbl_status = QtWidgets.QLabel(Dialog)
        self.lbl_status.setObjectName("lbl_status")
        self.verticalLayout.addWidget(self.lbl_status)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_next = QtWidgets.QPushButton(Dialog)
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout.addWidget(self.btn_next)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_protein_seq = QtWidgets.QLabel(Dialog)
        self.lbl_protein_seq.setObjectName("lbl_protein_seq")
        self.verticalLayout_2.addWidget(self.lbl_protein_seq)
        self.le_protein_seq = QtWidgets.QTextEdit(Dialog)
        self.le_protein_seq.setObjectName("le_protein_seq")
        self.verticalLayout_2.addWidget(self.le_protein_seq)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_back = QtWidgets.QPushButton(Dialog)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_2.addWidget(self.btn_back)
        self.btn_add = QtWidgets.QPushButton(Dialog)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_2.addWidget(self.btn_add)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_seq_name.setText(_translate("Dialog", "Enter new sequence name"))
        self.lbl_status.setText(_translate("Dialog", "Status"))
        self.btn_next.setText(_translate("Dialog", "Next"))
        self.lbl_protein_seq.setText(_translate("Dialog", "Enter protein sequence"))
        self.btn_back.setText(_translate("Dialog", "Back"))
        self.btn_add.setText(_translate("Dialog", "Add"))
