# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pyssa\gui\ui\forms\import_sequence_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 131)
        Dialog.setMinimumSize(QtCore.QSize(400, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 131))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_import_sequence = QtWidgets.QLineEdit(Dialog)
        self.txt_import_sequence.setFrame(True)
        self.txt_import_sequence.setReadOnly(False)
        self.txt_import_sequence.setObjectName("txt_import_sequence")
        self.horizontalLayout.addWidget(self.txt_import_sequence)
        self.btn_choose_fasta_file = QtWidgets.QToolButton(Dialog)
        self.btn_choose_fasta_file.setObjectName("btn_choose_fasta_file")
        self.horizontalLayout.addWidget(self.btn_choose_fasta_file)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lbl_status = QtWidgets.QLabel(Dialog)
        self.lbl_status.setObjectName("lbl_status")
        self.verticalLayout.addWidget(self.lbl_status)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        self.btn_import_sequence = QtWidgets.QPushButton(Dialog)
        self.btn_import_sequence.setObjectName("btn_import_sequence")
        self.horizontalLayout_2.addWidget(self.btn_import_sequence)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Choose an existing .fasta file"))
        self.btn_choose_fasta_file.setText(_translate("Dialog", "..."))
        self.lbl_status.setText(_translate("Dialog", "TextLabel"))
        self.btn_cancel.setText(_translate("Dialog", "Cancel"))
        self.btn_import_sequence.setText(_translate("Dialog", "Import"))
