# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dlgAddSequenceMonomer.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(432, 303)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_prot_name = QtWidgets.QLabel(Dialog)
        self.lbl_prot_name.setObjectName("lbl_prot_name")
        self.verticalLayout.addWidget(self.lbl_prot_name)
        self.txt_prot_name = QtWidgets.QLineEdit(Dialog)
        self.txt_prot_name.setObjectName("txt_prot_name")
        self.verticalLayout.addWidget(self.txt_prot_name)
        self.lbl_prot_name_status = QtWidgets.QLabel(Dialog)
        self.lbl_prot_name_status.setObjectName("lbl_prot_name_status")
        self.verticalLayout.addWidget(self.lbl_prot_name_status)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.btn_next = QtWidgets.QPushButton(Dialog)
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout.addWidget(self.btn_next)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_seq_name = QtWidgets.QLabel(Dialog)
        self.lbl_seq_name.setObjectName("lbl_seq_name")
        self.verticalLayout_2.addWidget(self.lbl_seq_name)
        self.txt_seq_name = QtWidgets.QTextEdit(Dialog)
        self.txt_seq_name.setObjectName("txt_seq_name")
        self.verticalLayout_2.addWidget(self.txt_seq_name)
        self.lbl_seq_name_status = QtWidgets.QLabel(Dialog)
        self.lbl_seq_name_status.setObjectName("lbl_seq_name_status")
        self.verticalLayout_2.addWidget(self.lbl_seq_name_status)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_back = QtWidgets.QPushButton(Dialog)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_2.addWidget(self.btn_back)
        self.btn_add_protein = QtWidgets.QPushButton(Dialog)
        self.btn_add_protein.setObjectName("btn_add_protein")
        self.horizontalLayout_2.addWidget(self.btn_add_protein)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_prot_name.setText(_translate("Dialog", "Enter protein name"))
        self.lbl_prot_name_status.setText(_translate("Dialog", "TextLabel"))
        self.btn_cancel.setText(_translate("Dialog", "Cancel"))
        self.btn_next.setText(_translate("Dialog", "Next"))
        self.lbl_seq_name.setText(_translate("Dialog", "Enter protein sequence"))
        self.lbl_seq_name_status.setText(_translate("Dialog", "TextLabel"))
        self.btn_back.setText(_translate("Dialog", "Back"))
        self.btn_add_protein.setText(_translate("Dialog", "Add"))
